version: "3"
services:
  mqtt:
      image: toke/mosquitto
      container_name: mqtt
      ports:
        - 1883:1883
      restart: unless-stopped
      networks:
        - my_net
  elk:
    image: iurebrandao/elk-connect:1.00
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - ".:/home/"
      - "./logstash/:/etc/logstash/conf.d/"
      - ".data/elasticsearch:/usr/share/elastisearch/data"
      - ".data/logstash:/var/lib/logstash"
      - ".data/kibana:/var/lib/kibana"
    networks:
      - my_net

  filebeat:
    build:
      context: filebeat/
    command: filebeat -e -strict.perms=false
    volumes:
      - /usr/share/app
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - my_net

networks:
  my_net:
    driver: bridge