version: "3"
services:
  mqtt:
      image: toke/mosquitto
      container_name: mqtt
      ports:
        - 1883:1883
      restart: unless-stopped
      networks:
        - my_net
  elk:
    image: iurebrandao/elk-python:1.03
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - ".:/home/"
      - "/usr/lib/python3/dist-packages/"
    networks:
      - my_net
  client:
    image: iurebrandao/python-client:1.01
    networks:
      - my_net

networks:
  my_net:
    driver: bridge